version: "3"
services:
  api:
    container_name: flask_api_container
    image: flask_api:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=True
      